version: "3.9"
services:
  order-service-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: "order_service_postgres_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"